//
// Created by Michal Ziobro on 25/07/2016.
//

#ifndef REMOTECONTROLLERAPI_CLIENT_IO_HELPER_H
#define REMOTECONTROLLERAPI_CLIENT_IO_HELPER_H

char * read_line(void);

#endif //REMOTECONTROLLERAPI_CLIENT_IO_HELPER_H
